apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: StatefulSet
metadata:
  name: kibishii-deployment
spec:
  serviceName: "kibishii"
  selector:
    matchLabels:
      app: kibishii
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: kibishii
    spec:
      containers:
      - name: kibishii
        image: gcr.io/velero-gcp/kibishii-worker:more-robust-for-low-perfomance-cluster-3086523-06.Feb.2023.09.32.12
        volumeMounts:
        - name: kibishii-data
          mountPath: /data
  volumeClaimTemplates:
  - metadata:
      name: kibishii-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "kibishii-storage-class"
      resources:
        requests:
          storage: 1Mi
